
@php
$footer = getContent('footer.content', true);
$medias = getContent('footer.element');
$policy = getContent('policy_pages.element');
@endphp
 <footer class="footer-section">
    <!--footer top start-->
    <!--for light footer add .footer-light class and for dark footer add .bg-dark .text-white class-->
    <div class="footer-top
    @if(Route::is('home') )
   footer-dark bg-dark-black
    @else
    footer-dark bg-dark-black
    @endif
    ptb-120">
        <div class="container">
            <div class="row justify-content-between">
                <div class="col-md-8 col-lg-4 mb-md-4 mb-lg-0">
                    <div class="footer-single-col">
                        <div class="footer-single-col mb-4">

                            <img src="{{asset('meta/img/footer-logo.png')}}" alt="logo" class="img-fluid logo-color" width="150px">
                        </div>
                        <p>BossMan is a online investment portal that makes it easy for everyone in the world to share in the profits generated by African’s Agriculture sector. Through simple investment, you can now earn huge returns with peace mind while helping build the continent's future.
                            <p style="font-size:14px; line-height:23px"> <span style="color: rgb(255, 204, 0)">Internationa Network:</span>  Bossman is present in countries like <u>Nigeria, Cameroon, South Africa, Canada, India, USA </u> and more</p>                        </p>

                        <form class="newsletter-form position-relative d-block d-lg-flex d-md-flex">
                            <input type="text" class="input-newsletter form-control me-2" placeholder="Enter your email" name="email" required="" autocomplete="off">
                            <input type="submit" value="Subscribe" data-wait="Please wait..." class="btn btn-primary mt-3 mt-lg-0 mt-md-0">
                        </form>

                    </div>
                </div>
                <div class="col-md-12 col-lg-7 mt-4 mt-md-0 mt-lg-0">
                    <div class="row">
                        <div class="col-md-4 col-lg-4 mt-4 mt-md-0 mt-lg-0 col-6">
                            <div class="footer-single-col">
                                <h3>Bossman Africa</h3>
                                <ul class="list-unstyled footer-nav-list mb-lg-0">
                                    <li><a  class="text-decoration-none" href="{{url('/')}}" target="_self">Investor Portal</a></li>
                                    <li><a  class="text-decoration-none" href="{{route('about')}}" target="_self">About Bossman Africa</a></li>
                                    <li><a  class="text-decoration-none" href="{{route('show.plan')}}" target="_self">Our Investor Plans</a></li>
                                    <li><a  class="text-decoration-none" href="{{route('faq')}}" target="_self">Technical Support</a></li>
                                    <li><a  class="text-decoration-none" href="https://ng-check.com/bossman-investment-limited/940705.html" target="blank">Bossman Investment Group</a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-md-4 col-lg-4 mt-4 mt-md-0 mt-lg-0 col-6">
                            <div class="footer-single-col">
                                <h3>Our Partners</h3>
                                <ul class="list-unstyled footer-nav-list mb-lg-0">
                                    <li><a href="https://www.harvestreturns.com/" class="text-decoration-none">Harvest Return</a></li>
                                    <li><a href="https://www.farmfundr.com/" class="text-decoration-none">Farm Funder</a></li>
                                    <li><a href="https://farmtogether.com/partners" class="text-decoration-none">Farm Together</a></li>
                                    <li><a href="#" class="text-decoration-none">United Banks of Africa</a></li>
                                    <li><a href="https://www.investsmall.co/" class="text-decoration-none">Invest Small</a>
                                    </li>
                                  
                                </ul>
                            </div>
                        </div>
                        <div class="col-md-4 col-lg-4 mt-4 mt-md-0 mt-lg-0">
                            <div class="footer-single-col">
                                <h3>Investor Resource</h3>
                                <ul class="list-unstyled footer-nav-list mb-lg-0">
                                    @foreach($policy as $singlePolicy)
                                    <li><a href="{{ route('privacy.page', ['slug'=> slug($singlePolicy->data_values->title), 'id'=>$singlePolicy->id]) }}" class="text-decoration-none">{{ __($singlePolicy->data_values->title) }}</a></li>
                                    @endforeach
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <!--footer top end-->

    <!--footer bottom start-->
    <div class="footer-bottom
    @if(Route::is('home') )
    footer-dark bg-dark-black
     @else
     footer-dark bg-dark-black
     @endif py-4">
        <div class="container">
            <div class="row justify-content-between align-items-center">
                <div class="col-12">
                    <p style="font-size: 11px">This site is operated by Bossman Inc.,"Bossman", which is a registered broker-dealer. Bossman gives investment advice, endorsement, analysis or recommendations with respect to all securities. All securities listed here are being offered by, and all information included on this site is the responsibility of Bossman. Bossman has taken steps to verify the adequacy, accuracy, or completeness of any information. Neither Bossman nor any of its officers, directors, agents and employees makes any warranty, express or implied, of any kind whatsoever related to the adequacy, accuracy or completeness of any information on this site of the use of information on this site. </p>
                </div>
                <div class="col-md-7 col-lg-7">
                    <div class="copyright-text">

                        <p class="mb-lg-0 mb-md-0">&copy; 2016-2022 Bossmanafrica.com Rights Reserved by the Bossman Invesment Corporation (BIC) </p>
                    </div>
                </div>
                <div class="col-md-4 col-lg-4">
                    <div class="footer-single-col text-start text-lg-end text-md-end">
                        <ul class="list-unstyled list-inline footer-social-list mb-0">
                            @foreach($medias as $media)
                            <li class="list-inline-item"><a href="{{ $media->data_values->soial_media_link }}" target="_blank"> @php echo $media->data_values->icon; @endphp </a></li>
                            @endforeach

                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--footer bottom end-->
</footer>
<!--footer section end-->
