@extends('web.layouts.master_dark')
@php
$about = getContent('about.content', true);
$aboutDatas = getContent('about.element');
$banner = getContent('banner.content', true);
$image = getContent('breadcumb.content', true);
$package = getContent('package.content', true);

@endphp
@section('content')
<style>
    .bg-dark {
        background-color: #077f28 !important;
    }
    .crypto-team-social li a {
    color: #000000;
    font-weight: 800;
}
.footer-single-col h3 {
    font-size: 18px;
    font-weight: 600;
    margin-bottom: 36px;
    color: #0cd444;
}
h1, .display-1, .h2, .display-2, .h3, .display-3, .h4, .display-4, .h5, .display-5, .h6, .display-6, h1, h2, h3, h4, h5, h6 {

    color: #000000;
}
    .text-primary {
        color: #077f28 !important;
    }
    .crypto-team-info p {
    color: #151414;
    font-weight: 500;
}
    .img-rounded {
        border-radius: 20px
    }

    .btn-primary {
        color: #1d1d1d;
    background: #fad507 !important;
    text-transform: uppercase;
        border-color: #fad507;
        -webkit-box-shadow: 0 11px 18px -8px rgb(23 92 255 / 60%);
        box-shadow: 0 11px 18px -8px rgb(23 92 255 / 60%);
    }

</style>
<section class="hero-section ptb-120 text-white bg-dark" style="background: url('{{asset('meta/img/dot-world.svg')}}')no-repeat center left">
    <div class="container">
        <div class="row justify-content-center text-center text-lg-start align-items-center">
            <div class="col-lg-6 col-md-10">
                <div class="hero-content-wrap mt-5 mt-lg-0 mt-xl-0">
                    <h1 class="fw-bold display-5" data-aos="fade-up">Welcome to Help Farmers</h1>
                    <p class="lead" data-aos="fade-up">BossMan is a mutual fund investment portal and management system that gives investors access to the over $100 billion a year profits generated by Africa’s Agricultural sector. Through simple investment, you can earn huge returns with peace of mind while helping build the continent's future.</p>
                    <div class="action-btns mt-5" data-aos="fade-up" data-aos-delay="50">
                        <a href="{{route('register')}}" class="btn btn-primary me-3">Become an Investor</a>
                        <a href="https://bossmanafrica.com/about-bossman" class="btn btn-outline-light">Learn more about Bossman</a>
                    </div>

                </div>
            </div>
            <div class="col-lg-6 col-md-8">
                <div class="hero-img-wrap position-relative app-screen-bg mt-5" style="background-image: url({{asset('meta/img/dot-world.svg')}})" data-aos="fade-up" data-aos-delay="200">
                    <img src="{{asset('meta/img/home_1.png')}}" alt="hero image" class="img-fluid position-relative z-5">
                </div>
            </div>
        </div>
    </div>
</section>
<!--hero section end-->

<!--feature section start-->
<section class="feature-section ptb-120" style="background: #29ff6429;">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-6 col-md-12">
                <div class="section-heading text-center" data-aos="fade-up">
                    <h4 class="text-primary h5">Start Earning Today</h4>
                    <h2>Let Your Money Work For You In The Agro Industry Today</h2>
                    <p>Relax while our experts give your high returns from the AgTech and Africa Food Industry</p>
                </div>
            </div>
        </div>
        <div class="row align-items-center">
            <div class="col-lg-4 col-md-6">
                <div class="position-relative" data-aos="fade-up" data-aos-delay="50">
                    <div class="cta-card rounded-custom text-center custom-shadow p-5 bg-white mt-4 mt-lg-0 mt-md-0 z-2">
                        <div class="feature-icon d-inline-block bg-primary-soft rounded-circle mb-32">
                            <i class="fad fa-shield-alt text-primary fa-2x"></i>
                        </div>
                        <h3 class="h5">$23,850,573</h3>
                        <p class="mb-0">Over 63 million dollars in first quarter payout of 2022</p>
                    </div>
                    <!--pattern start-->
                    <div class="dot-shape-bg position-absolute z--1 left--40 top--40">
                        <img src="{{asset('meta/img/dots.svg')}}" alt="shape">
                    </div>
                    <!--pattern end-->
                </div>
            </div>
            <div class="col-lg-4 col-md-6">
                <div class="position-relative" data-aos="fade-up" data-aos-delay="100">
                    <div class="cta-card rounded-custom text-center custom-shadow p-5 bg-white mt-4 mt-lg-0 mt-md-0">
                        <div class="feature-icon d-inline-block bg-danger-soft rounded-circle mb-32">
                            <i class="fad fa-comment-alt-smile text-danger fa-2x"></i>
                        </div>
                        <h3 class="h5">11,700</h3>
                        <p class="mb-0">More than 41 thousand happy investors cashing out Big</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6">
                <div class="position-relative" data-aos="fade-up" data-aos-delay="150">
                    <div class="cta-card rounded-custom text-center custom-shadow p-5 bg-white mt-4 mt-lg-0">
                        <div class="feature-icon d-inline-block bg-success-soft rounded-circle mb-32">
                            <i class="fad fa-grin-stars text-success fa-2x"></i>
                        </div>
                        <h3 class="h5">$46,372,500</h3>
                        <p class="mb-0">Don't miss out on Bossman next investor payout this June</p>
                    </div>
                    <!--pattern start-->
                    <div class="dot-shape-bg position-absolute z--1 right--40 bottom--40">
                        <img src="{{asset('meta/img/dots.svg')}}" alt="shape">
                    </div>
                    <!--pattern end-->
                </div>
            </div>
        </div>
    </div>
</section>
<!--feature section end-->

<!--feature section start-->
<section class="feature-section ptb-120">
    <div class="container">
        <div class="row align-items-lg-center justify-content-between">
            <div class="col-lg-5 order-lg-2 mb-7 mb-lg-0">
                <div class="mb-4" data-aos="fade-up">
                    <h2>High Investment Returns in a $100 Billion a Year Market</h2>
                    <p>We follow the trends, invest in the technology, partner with the locals and have access to high returns in exports, trades and securities. $56 billion in improts and over $110 in exports, your can save high returns weekly.</p>
                </div>

            </div>
            <div class="col-lg-6 order-lg-1">

                <img class="position-relative z-2 w-100 h-auto img-rounded" src="{{asset('meta/img/bossman_1.jpeg')}}" alt="Image Description">



            </div>
        </div>
    </div>
</section>
@php
    $feature = getContent('feature.content', true);
    $features = getContent('feature.element');
@endphp

<section class="feature-section ptb-120" style="background: url({{asset('meta/img/greenfield.jpeg')}})no-repeat center center;display: block;
max-width: 100%;
height: auto;
line-height: 1;
background-size:cover">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-6 col-md-12">
                <div class="section-heading text-center" data-aos="fade-up">
                    <h4 class="text-white h5">Join Millions Of Other Investors.</h4>
                    <h2 class="text-white">{{ __(@$feature->data_values->heading) }}</h2>
                    <p class="text-white">Work with the world’s biggest network of independent experts to invest in bold and impactful technologies, and processes rapidly transforming our food and agriculture system.</p>
                </div>
            </div>
        </div>
        <div class="row align-items-center">
            @foreach($features as $singleFeature)
            <div class="col-lg-3 col-md-4">
                <div class="position-relative" data-aos="fade-up" data-aos-delay="50">
                    <div class="cta-card rounded-custom text-center custom-shadow p-5 bg-white mt-4 mt-lg-0 mt-md-0 z-2">
                        <div class="feature-icon d-inline-block bg-primary-soft rounded-circle mb-32">
                            @php echo $singleFeature->data_values->icon; @endphp
                        </div>
                        <h3 class="h5 text-primary">{{ __(@$singleFeature->data_values->title) }}</h3>
                        <p class="mb-0"> {{ __(@$singleFeature->data_values->text) }}</p>
                    </div>

                </div>
            </div>
            @endforeach
        </div>
    </div>
</section>
@php
    $tppInvestor = getContent('topInvestor.content', true);
    $tppInvestors = getContent('topInvestor.element');
@endphp



<!-- Team Start
<section class="crypto-team bg-dark ptb-60">
    <div class="container">
        <div class="row align-items-center mb-30">
            <div class="col-lg-5 col-md-8">
                <div class="section-title">
                    <h2 class="text-white mb-4">{{ __(@$tppInvestor->data_values->heading) }}</h2>
                    <p class="">
                        Our platform offers a range of investment options, with weekly returns ranging from 10% to 60% per week. Our top investors are earning hugely on our platform.
                    </p>
                </div>
            </div>
            <div class="col-lg-7 col-md-4">

            </div>
        </div>
        <div class="row">
           @include('web.partials.team_members')
        </div>
    </div>
</section>
 Team End -->

<!--process section start-->
<section class="process-section bg-light ptb-120">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-6 col-md-12">
                <div class="section-heading text-center" data-aos="fade-up">
                    <h4 class="h5 text-primary"> setup</h4>
                    <h2>A Simple & Effortless Process</h2>
                    <p>Have your personalized management system for your profits.</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="setup-process-wrap">
                    <ul class="setup-process-list list-unstyled text-center mb-0">
                        <li class="setup-process-item py-4 px-2" data-aos="fade-up">
                            <div class="setup-process-icon mb-4">
                                <i class="fal fa-download fa-2x text-primary"></i>
                            </div>
                            <span class="process-tag badge bg-primary-soft py-1 px-3 small fw-bold text-primary rounded-custom">Step 1</span>
                            <h6 class="mt-3 mb-0">Open Account Service</h6>
                        </li>
                        <li class="setup-process-item py-4 px-2" data-aos="fade-up" data-aos-delay="50">
                            <div class="setup-process-icon mb-4">
                                <i class="fal fa-street-view fa-2x text-primary"></i>
                            </div>
                            <span class="process-tag badge bg-primary-soft py-1 px-3 small fw-bold text-primary rounded-custom">Step 2</span>
                            <h6 class="mt-3 mb-0">Free Registration</h6>
                        </li>
                        <li class="setup-process-item py-4 px-2" data-aos="fade-up" data-aos-delay="100">
                            <div class="setup-process-icon mb-4">
                                <i class="fal fa-bezier-curve fa-2x text-primary"></i>
                            </div>
                            <span class="process-tag badge bg-primary-soft py-1 px-3 small fw-bold text-primary rounded-custom">Step 3</span>
                            <h6 class="mt-3 mb-0">Verify Account</h6>
                        </li>
                        <li class="setup-process-item py-4 px-2" data-aos="fade-up" data-aos-delay="150">
                            <div class="setup-process-icon mb-4">
                                <i class="fal fa-user-shield fa-2x text-primary"></i>
                            </div>
                            <span class="process-tag badge bg-primary-soft py-1 px-3 small fw-bold text-primary rounded-custom">Step 4</span>
                            <h6 class="mt-3 mb-0">Start Earning</h6>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
<!--process section end-->



<section class="contact-us ptb-120 position-relative overflow-hidden" style="background-color:#eeffeb">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-md-12 mx-auto">
                <div class="section-heading text-center" data-aos="fade-up">
                    <h4 class="h5 text-primary">Investor Resources</h4>
                    <h2>Bossman Updates & Resources</h2>
                    <p>Stay current with top stories on our platform and the Agriculture Industry in Africa</p>
                </div>
            </div>
        </div>
        <div class="row justify-content-between">
            @include('web.partials.blog_section')
        </div>
</section>



<!--contact us section start-->
<section class="contact-us ptb-120 position-relative overflow-hidden">
    <div class="container">
        <div class="row justify-content-between">
            <div class="col-xl-5 col-lg-5 col-md-12">
                <div class="section-heading" data-aos="fade-up">
                    <h4 class="h5 text-primary">Our International Credebility</h4>
                    <h2>Trusted and Endorsed Partners. </h2>
                    <p>Bossman Investment platform is a modern and innovative solution for the way we think about investment. Over the years, we have built the brand with a vision to innovate the financial planning space. </p>
                    <div class="media mt-3">
                        <img src="{{asset('meta/img/partners.png')}}" alt="" class="img-fluid">
                    </div>
                </div>
                <div class="row justify-content-between pb-5">
                    <div class="col-sm-6 mb-4 mb-md-0 mb-lg-0" data-aos="fade-up" data-aos-delay="50">
                        <div class="icon-box d-inline-block rounded-circle bg-primary-soft">
                            <i class="fas fa-phone fa-2x text-primary"></i>
                        </div>
                        <div class="contact-info">
                            <h5>Call Us</h5>
                            <p>Questions about our platform, farmlands or investments? Call for support</p>
                            <a href="" class="read-more-link text-decoration-none"><i class="far fa-phone me-2"></i> +1 (301) 686 5226</a>
                        </div>
                    </div>
                    <div class="col-sm-6" data-aos="fade-up" data-aos-delay="100">
                        <div class="icon-box d-inline-block rounded-circle bg-danger-soft">
                            <i class="fas fa-comment-alt-lines fa-2x text-danger"></i>
                        </div>
                        <div class="contact-info">
                            <h5>Chat Us</h5>
                            <p>Our support will help you from
                                <strong>9am to 5pm EST.</strong></p>
                            <a href="#" class="read-more-link text-decoration-none"><i class="far fa-comment-alt-dots me-2"></i> Live Chat Now</a>
                        </div>
                    </div>

                </div>
            </div>
            <div class="col-xl-5 col-lg-7 col-md-12">
                <div class="register-wrap p-5 bg-white shadow rounded-custom position-relative" data-aos="fade-up" data-aos-delay="150">
                    @php
$footer = getContent('footer.content', true);
$medias = getContent('footer.element');
$policy = getContent('policy_pages.element');
@endphp
                      <form method="POST" action="{{ route('register') }}" class="register-form position-relative z-5">
                            @csrf
                            <h3 class="mb-5 fw-medium">Signup to join thousands of investors across Africa who are earning on Bossman</h3>
                            @if(session()->get('reference') != null)
                            <div class="form-group row">
                                <div class="col-md-6">
                                    <label for="referenceBy" class="col-md-4 col-form-label text-md-right">@lang('Reference By')</label>
                                    <input type="text" name="referBy" id="referenceBy" class="form-control" value="{{session()->get('reference')}}" readonly>
                                </div>
                            </div>
                            @endif
                            <div class="row mb-2">
                                <div class="col-md-6">
                                    <label for="email" class="mb-1">Firstname <span class="text-danger">*</span></label>
                                    <input id="firstname" type="text" class="form-control" name="firstname" value="{{ old('firstname') }}" placeholder="@lang('First Name')" required>
                                </div>

                                <div class="col-md-6">
                                    <label for="email" class="mb-1">Last Name <span class="text-danger">*</span></label>
                                    <input id="lastname" type="text" class="form-control" placeholder="@lang('Last Name')" name="lastname" value="{{ old('lastname') }}" required>
                                </div>
                            </div>
                            <div class="row mb-2">
                                <div class="col-sm-6 ">
                                    <label for="email" class="mb-1">Select Your Country <span class="text-danger">*</span></label>
                                    <div class="input-group mb-3">
                                        <select name="country" id="country" class="form-control">
                                            <option value="">@lang('Select your country')</option>

                                            <option value="Afganistan">Afghanistan</option>
                                            <option value="Albania">Albania</option>
                                            <option value="Algeria">Algeria</option>
                                            <option value="American Samoa">American Samoa</option>
                                            <option value="Andorra">Andorra</option>
                                            <option value="Angola">Angola</option>
                                            <option value="Anguilla">Anguilla</option>
                                            <option value="Antigua & Barbuda">Antigua & Barbuda</option>
                                            <option value="Argentina">Argentina</option>
                                            <option value="Armenia">Armenia</option>
                                            <option value="Aruba">Aruba</option>
                                            <option value="Australia">Australia</option>
                                            <option value="Austria">Austria</option>
                                            <option value="Azerbaijan">Azerbaijan</option>
                                            <option value="Bahamas">Bahamas</option>
                                            <option value="Bahrain">Bahrain</option>
                                            <option value="Bangladesh">Bangladesh</option>
                                            <option value="Barbados">Barbados</option>
                                            <option value="Belarus">Belarus</option>
                                            <option value="Belgium">Belgium</option>
                                            <option value="Belize">Belize</option>
                                            <option value="Benin">Benin</option>
                                            <option value="Bermuda">Bermuda</option>
                                            <option value="Bhutan">Bhutan</option>
                                            <option value="Bolivia">Bolivia</option>
                                            <option value="Bonaire">Bonaire</option>
                                            <option value="Bosnia & Herzegovina">Bosnia & Herzegovina</option>
                                            <option value="Botswana">Botswana</option>
                                            <option value="Brazil">Brazil</option>
                                            <option value="British Indian Ocean Ter">British Indian Ocean Ter</option>
                                            <option value="Brunei">Brunei</option>
                                            <option value="Bulgaria">Bulgaria</option>
                                            <option value="Burkina Faso">Burkina Faso</option>
                                            <option value="Burundi">Burundi</option>
                                            <option value="Cambodia">Cambodia</option>
                                            <option data-mobile_code="237" value="Cameroon" data-code="CM" selected>Cameroon</option>
                                            <option value="Canada">Canada</option>
                                            <option value="Canary Islands">Canary Islands</option>
                                            <option value="Cape Verde">Cape Verde</option>
                                            <option value="Cayman Islands">Cayman Islands</option>
                                            <option value="Central African Republic">Central African Republic</option>
                                            <option value="Chad">Chad</option>
                                            <option value="Channel Islands">Channel Islands</option>
                                            <option value="Chile">Chile</option>
                                            <option value="China">China</option>
                                            <option value="Christmas Island">Christmas Island</option>
                                            <option value="Cocos Island">Cocos Island</option>
                                            <option value="Colombia">Colombia</option>
                                            <option value="Comoros">Comoros</option>
                                            <option value="Congo">Congo</option>
                                            <option value="Cook Islands">Cook Islands</option>
                                            <option value="Costa Rica">Costa Rica</option>
                                            <option value="Cote DIvoire">Cote DIvoire</option>
                                            <option value="Croatia">Croatia</option>
                                            <option value="Cuba">Cuba</option>
                                            <option value="Curaco">Curacao</option>
                                            <option value="Cyprus">Cyprus</option>
                                            <option value="Czech Republic">Czech Republic</option>
                                            <option value="Denmark">Denmark</option>
                                            <option value="Djibouti">Djibouti</option>
                                            <option value="Dominica">Dominica</option>
                                            <option value="Dominican Republic">Dominican Republic</option>
                                            <option value="East Timor">East Timor</option>
                                            <option value="Ecuador">Ecuador</option>
                                            <option value="Egypt">Egypt</option>
                                            <option value="El Salvador">El Salvador</option>
                                            <option value="Equatorial Guinea">Equatorial Guinea</option>
                                            <option value="Eritrea">Eritrea</option>
                                            <option value="Estonia">Estonia</option>
                                            <option value="Ethiopia">Ethiopia</option>
                                            <option value="Falkland Islands">Falkland Islands</option>
                                            <option value="Faroe Islands">Faroe Islands</option>
                                            <option value="Fiji">Fiji</option>
                                            <option value="Finland">Finland</option>
                                            <option value="France">France</option>
                                            <option value="French Guiana">French Guiana</option>
                                            <option value="French Polynesia">French Polynesia</option>
                                            <option value="French Southern Ter">French Southern Ter</option>
                                            <option value="Gabon">Gabon</option>
                                            <option value="Gambia">Gambia</option>
                                            <option value="Georgia">Georgia</option>
                                            <option value="Germany">Germany</option>
                                            <option value="Ghana">Ghana</option>
                                            <option value="Gibraltar">Gibraltar</option>
                                            <option value="Great Britain">Great Britain</option>
                                            <option value="Greece">Greece</option>
                                            <option value="Greenland">Greenland</option>
                                            <option value="Grenada">Grenada</option>
                                            <option value="Guadeloupe">Guadeloupe</option>
                                            <option value="Guam">Guam</option>
                                            <option value="Guatemala">Guatemala</option>
                                            <option value="Guinea">Guinea</option>
                                            <option value="Guyana">Guyana</option>
                                            <option value="Haiti">Haiti</option>
                                            <option value="Hawaii">Hawaii</option>
                                            <option value="Honduras">Honduras</option>
                                            <option value="Hong Kong">Hong Kong</option>
                                            <option value="Hungary">Hungary</option>
                                            <option value="Iceland">Iceland</option>
                                            <option value="Indonesia">Indonesia</option>
                                            <option value="India">India</option>
                                            <option value="Iran">Iran</option>
                                            <option value="Iraq">Iraq</option>
                                            <option value="Ireland">Ireland</option>
                                            <option value="Isle of Man">Isle of Man</option>
                                            <option value="Israel">Israel</option>
                                            <option value="Italy">Italy</option>
                                            <option value="Jamaica">Jamaica</option>
                                            <option value="Japan">Japan</option>
                                            <option value="Jordan">Jordan</option>
                                            <option value="Kazakhstan">Kazakhstan</option>
                                            <option value="Kenya">Kenya</option>
                                            <option value="Kiribati">Kiribati</option>
                                            <option value="Korea North">Korea North</option>
                                            <option value="Korea Sout">Korea South</option>
                                            <option value="Kuwait">Kuwait</option>
                                            <option value="Kyrgyzstan">Kyrgyzstan</option>
                                            <option value="Laos">Laos</option>
                                            <option value="Latvia">Latvia</option>
                                            <option value="Lebanon">Lebanon</option>
                                            <option value="Lesotho">Lesotho</option>
                                            <option value="Liberia">Liberia</option>
                                            <option value="Libya">Libya</option>
                                            <option value="Liechtenstein">Liechtenstein</option>
                                            <option value="Lithuania">Lithuania</option>
                                            <option value="Luxembourg">Luxembourg</option>
                                            <option value="Macau">Macau</option>
                                            <option value="Macedonia">Macedonia</option>
                                            <option value="Madagascar">Madagascar</option>
                                            <option value="Malaysia">Malaysia</option>
                                            <option value="Malawi">Malawi</option>
                                            <option value="Maldives">Maldives</option>
                                            <option value="Mali">Mali</option>
                                            <option value="Malta">Malta</option>
                                            <option value="Marshall Islands">Marshall Islands</option>
                                            <option value="Martinique">Martinique</option>
                                            <option value="Mauritania">Mauritania</option>
                                            <option value="Mauritius">Mauritius</option>
                                            <option value="Mayotte">Mayotte</option>
                                            <option value="Mexico">Mexico</option>
                                            <option value="Midway Islands">Midway Islands</option>
                                            <option value="Moldova">Moldova</option>
                                            <option value="Monaco">Monaco</option>
                                            <option value="Mongolia">Mongolia</option>
                                            <option value="Montserrat">Montserrat</option>
                                            <option value="Morocco">Morocco</option>
                                            <option value="Mozambique">Mozambique</option>
                                            <option value="Myanmar">Myanmar</option>
                                            <option value="Nambia">Nambia</option>
                                            <option value="Nauru">Nauru</option>
                                            <option value="Nepal">Nepal</option>
                                            <option value="Netherland Antilles">Netherland Antilles</option>
                                            <option value="Netherlands">Netherlands (Holland, Europe)</option>
                                            <option value="Nevis">Nevis</option>
                                            <option value="New Caledonia">New Caledonia</option>
                                            <option value="New Zealand">New Zealand</option>
                                            <option value="Nicaragua">Nicaragua</option>
                                            <option value="Niger">Niger</option>
                                            <option value="Nigeria">Nigeria</option>
                                            <option value="Niue">Niue</option>
                                            <option value="Norfolk Island">Norfolk Island</option>
                                            <option value="Norway">Norway</option>
                                            <option value="Oman">Oman</option>
                                            <option value="Pakistan">Pakistan</option>
                                            <option value="Palau Island">Palau Island</option>
                                            <option value="Palestine">Palestine</option>
                                            <option value="Panama">Panama</option>
                                            <option value="Papua New Guinea">Papua New Guinea</option>
                                            <option value="Paraguay">Paraguay</option>
                                            <option value="Peru">Peru</option>
                                            <option value="Phillipines">Philippines</option>
                                            <option value="Pitcairn Island">Pitcairn Island</option>
                                            <option value="Poland">Poland</option>
                                            <option value="Portugal">Portugal</option>
                                            <option value="Puerto Rico">Puerto Rico</option>
                                            <option value="Qatar">Qatar</option>
                                            <option value="Republic of Montenegro">Republic of Montenegro</option>
                                            <option value="Republic of Serbia">Republic of Serbia</option>
                                            <option value="Reunion">Reunion</option>
                                            <option value="Romania">Romania</option>
                                            <option value="Russia">Russia</option>
                                            <option value="Rwanda">Rwanda</option>
                                            <option value="St Barthelemy">St Barthelemy</option>
                                            <option value="St Eustatius">St Eustatius</option>
                                            <option value="St Helena">St Helena</option>
                                            <option value="St Kitts-Nevis">St Kitts-Nevis</option>
                                            <option value="St Lucia">St Lucia</option>
                                            <option value="St Maarten">St Maarten</option>
                                            <option value="St Pierre & Miquelon">St Pierre & Miquelon</option>
                                            <option value="St Vincent & Grenadines">St Vincent & Grenadines</option>
                                            <option value="Saipan">Saipan</option>
                                            <option value="Samoa">Samoa</option>
                                            <option value="Samoa American">Samoa American</option>
                                            <option value="San Marino">San Marino</option>
                                            <option value="Sao Tome & Principe">Sao Tome & Principe</option>
                                            <option value="Saudi Arabia">Saudi Arabia</option>
                                            <option value="Senegal">Senegal</option>
                                            <option value="Seychelles">Seychelles</option>
                                            <option value="Sierra Leone">Sierra Leone</option>
                                            <option value="Singapore">Singapore</option>
                                            <option value="Slovakia">Slovakia</option>
                                            <option value="Slovenia">Slovenia</option>
                                            <option value="Solomon Islands">Solomon Islands</option>
                                            <option value="Somalia">Somalia</option>
                                            <option value="South Africa">South Africa</option>
                                            <option value="Spain">Spain</option>
                                            <option value="Sri Lanka">Sri Lanka</option>
                                            <option value="Sudan">Sudan</option>
                                            <option value="Suriname">Suriname</option>
                                            <option value="Swaziland">Swaziland</option>
                                            <option value="Sweden">Sweden</option>
                                            <option value="Switzerland">Switzerland</option>
                                            <option value="Syria">Syria</option>
                                            <option value="Tahiti">Tahiti</option>
                                            <option value="Taiwan">Taiwan</option>
                                            <option value="Tajikistan">Tajikistan</option>
                                            <option value="Tanzania">Tanzania</option>
                                            <option value="Thailand">Thailand</option>
                                            <option value="Togo">Togo</option>
                                            <option value="Tokelau">Tokelau</option>
                                            <option value="Tonga">Tonga</option>
                                            <option value="Trinidad & Tobago">Trinidad & Tobago</option>
                                            <option value="Tunisia">Tunisia</option>
                                            <option value="Turkey">Turkey</option>
                                            <option value="Turkmenistan">Turkmenistan</option>
                                            <option value="Turks & Caicos Is">Turks & Caicos Is</option>
                                            <option value="Tuvalu">Tuvalu</option>
                                            <option value="Uganda">Uganda</option>
                                            <option value="United Kingdom">United Kingdom</option>
                                            <option value="Ukraine">Ukraine</option>
                                            <option value="United Arab Erimates">United Arab Emirates</option>
                                            <option value="United States of America">United States of America</option>
                                            <option value="Uraguay">Uruguay</option>
                                            <option value="Uzbekistan">Uzbekistan</option>
                                            <option value="Vanuatu">Vanuatu</option>
                                            <option value="Vatican City State">Vatican City State</option>
                                            <option value="Venezuela">Venezuela</option>
                                            <option value="Vietnam">Vietnam</option>
                                            <option value="Virgin Islands (Brit)">Virgin Islands (Brit)</option>
                                            <option value="Virgin Islands (USA)">Virgin Islands (USA)</option>
                                            <option value="Wake Island">Wake Island</option>
                                            <option value="Wallis & Futana Is">Wallis & Futana Is</option>
                                            <option value="Yemen">Yemen</option>
                                            <option value="Zaire">Zaire</option>
                                            <option value="Zambia">Zambia</option>
                                            <option value="Zimbabwe">Zimbabwe</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <label for="company" class="mb-1">Phone number</label>
                                    <div class="input-group ">
                                        <div class="input-group-prepend">

                                            <input type="hidden" name="mobile_code" value="237">
                                            <input type="hidden" name="country_code" value="CM">
                                        </div>
                                        <input type="text" name="mobile" id="mobile" value="{{ old('mobile') }}" class="form-control checkUser" placeholder="@lang('Your Phone Number')">
                                    </div>
                                    <small class="text-danger mobileExist"></small>
                                </div>
                            </div>
                            <div class="row mb-2">

                                <div class="col-md-6">
                                    <label for="company" class="mb-1">Enter Username</label>
                                    <input id="username" type="text" class="form-control checkUser" placeholder="@lang('Enter a username')" name="username" value="{{ old('username') }}" required>
                                    <small class="text-danger usernameExist"></small>
                                </div>
                                <div class="col-md-6">
                                    <label for="company" class="mb-1">Your Email</label>
                                    <input id="email" type="email" class="form-control checkUser" placeholder="@lang('Email address')" name="email" value="{{ old('email') }}" required>
                                </div>
                            </div>

                            <div class="col-sm-12 hover-input-popup">
                                <label for="password" class="mb-1">Password <span class="text-danger">*</span></label>

                                    <input type="password" name="password" class="form-control pwd" id="login_password" placeholder="{{__('Enter Password')}}"  minlength="6" data-msg-required="{{ __('Required.') }}" data-msg-minlength="{{ __('At least :num chars.', ['num' => 6]) }}" required>
                                    @if($general->secure_password)
                                    <div class="input-popup">
                                        <p class="error lower">@lang('1 small letter minimum')</p>
                                        <p class="error capital">@lang('1 capital letter minimum')</p>
                                        <p class="error number">@lang('1 number minimum')</p>
                                        <p class="error special">@lang('1 special character minimum')</p>
                                        <p class="error minimum">@lang('6 character password')</p>
                                    </div>
                                    @endif


                            </div>
                            <div class="col-12 mb-2">
                                <label for="password" class="mb-1">Confirm Password <span class="text-danger">*</span></label>
                                    <input id="password-confirm" type="password" placeholder="@lang('Confirm Password')" class="form-control" name="password_confirmation" required autocomplete="new-password">
                            </div>
                            @if($general->agree)
                            <div class="col-12">
                                <div class="form-check d-flex">
                                    <input class="form-check-input me-2" name="agree" id="agree" type="checkbox" required="required" data-msg-required="{{ __("You should accept our terms and policy.") }}">
                                    <label for="agree">@lang('I agree with') @foreach($policy as $singlePolicy)
                                        <a href="{{ route('privacy.page', ['slug'=> slug($singlePolicy->data_values->title), 'id'=>$singlePolicy->id]) }}">{{ __($singlePolicy->data_values->title) }},</a>
                                        @endforeach</label>
                                </div>
                            </div>
                            @endif
                            <div class="col-12">
                                <button type="submit" class="btn btn-primary mt-4 d-block w-100">Submit</button>
                            </div>
                    </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="bg-dark position-absolute bottom-0 h-25 bottom-0 left-0 right-0 z--1 py-5" style="background: url({{asset('meta/img/greenfield.jpeg')}})no-repeat center center;display: block;
    max-width: 100%;
    height: auto;
    line-height: 1;
    background-color:#000">
        <div class="bg-circle rounded-circle circle-shape-3 position-absolute bg-dark-light left-5"></div>
        <div class="bg-circle rounded-circle circle-shape-1 position-absolute bg-warning right-5"></div>
    </div>
</section>
<!--contact us section end-->

@endsection
