@extends('frontend.layouts.master_dark')

@section('content')

        <!--page header section start-->
        <section class="page-header position-relative overflow-hidden ptb-120 bg-dark" style="background: url('assets/img/page-header-bg.svg')no-repeat bottom left">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-8 col-12">
                        <h1 class="fw-bold display-5">{{$blog->title}}</h1>
                    </div>
                </div>
                <div class="bg-circle rounded-circle circle-shape-3 position-absolute bg-dark-light right-5"></div>
            </div>
        </section>
        <!--page header section end-->

        <!--blog details section start-->
        <section class="blog-details ptb-120">
            <div class="container">
                <div class="row justify-content-between">
                    <div class="col-lg-8 pe-lg-5">
                        <div class="vehron-postDetails img">
                            <img src="{{asset($blog->image)}}" alt="" class="img-fluid">
                        </div>
                        <div class="blog-details-wrap mt-4">
                            {!!$blog->description!!}
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="author-wrap text-center bg-light p-5 sticky-sidebar rounded-custom mt-5 mt-lg-0">
                            <img src="{{asset('meta/img/favicon.png')}}" alt="author" width="120" class="img-fluid shadow-sm rounded-circle">
                            <div class="author-info my-4">
                                <h5 class="mb-0">Media Editor</h5>
                                <span class="small">Bossman Capital, USA</span>
                            </div>
                            <p>Bossman is a online investment portal that makes it easy for everyone in the world to share in the profits generated by African’s Agriculture sector. Through simple investment, you can now earn huge returns with peace mind while helping build the continent's future.

                            </p>

                        </div>
                    </div>
                </div>
            </div>

        <!--related blog start-->
        <section class="related-blog-list ptb-120 bg-light">
            <div class="container">
                <div class="row align-items-center justify-content-between">
                    <div class="col-lg-4 col-md-12">
                        <div class="section-heading">
                            <h4 class="h5 text-primary">Related News</h4>
                            <h2>More Latest News and Updates on {{env('APP_NAME')}}</h2>
                        </div>
                    </div>
                    <div class="col-lg-7 col-md-12">
                        <div class="text-start text-lg-end mb-4 mb-lg-0 mb-xl-0">

                        </div>
                    </div>
                </div>
                <div class="row">
                    @forelse ( $related_stories as $related)
                    <div class="col-lg-4 col-md-6">
                        <div class="single-article rounded-custom mb-4 mb-lg-0">
                            <a href="{{route('front.blog', $related->id)}}" class="article-img">
                                <img src="{{asset($related->image)}}" alt="article" class="img-fluid">
                            </a>
                            <div class="article-content p-4">

                                <a href="{{route('front.blog', $related->id)}}">
                                    <h2 class="h5 article-title limit-2-line-text">{{$related->title}}</h2>
                                </a>
                                <p class="limit-2-line-text">{{$related->excerpt}}</p>



                            </div>
                        </div>
                    </div>
                    @empty

                    @endforelse


                </div>
            </div>
        </section>
        <!--related blog end-->

@endsection
